..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 00_arctic_calibration.png ..\sbgck-dev-game\src\boards\Arctic-base.png	00_arctic_x_cut_calibration.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 01_arctic_color_checker.png ..\sbgck-dev-game\src\boards\Arctic-base.png	01_arctic_x_cut_color_checker.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 01_arctic_x_cut_color_checker.png ..\sbgck-dev-game\game\assets\color_checker.png	01_arctic_x_cut_color_checker_isolated.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 10_arctic_red_control_post.png ..\sbgck-dev-game\src\boards\Arctic-base.png	10_arctic_x_cut_red_control_post.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 11_arctic_red_living_room.png ..\sbgck-dev-game\src\boards\Arctic-base.png	11_arctic_x_cut_red_living_room.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 12_arctic_red_storage_room.png ..\sbgck-dev-game\src\boards\Arctic-base.png	12_arctic_x_cut_red_storage_room.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 13_arctic_red_bridge.png ..\sbgck-dev-game\src\boards\Arctic-base.png	13_arctic_x_cut_red_bridge.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 20_arctic_green_control_post.png ..\sbgck-dev-game\src\boards\Arctic-base.png	20_arctic_x_cut_green_control_post.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 21_arctic_green_living_room.png ..\sbgck-dev-game\src\boards\Arctic-base.png	21_arctic_x_cut_green_living_room.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 22_arctic_green_storage_room.png ..\sbgck-dev-game\src\boards\Arctic-base.png	22_arctic_x_cut_green_storage_room.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 23_arctic_green_bridge.png ..\sbgck-dev-game\src\boards\Arctic-base.png	23_arctic_x_cut_green_bridge.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 30_arctic_blue_control_post.png ..\sbgck-dev-game\src\boards\Arctic-base.png	30_arctic_x_cut_blue_control_post.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 31_arctic_blue_living_room.png ..\sbgck-dev-game\src\boards\Arctic-base.png	31_arctic_x_cut_blue_living_room.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 32_arctic_blur_storage_room.png ..\sbgck-dev-game\src\boards\Arctic-base.png	32_arctic_x_cut_blur_storage_room.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 33_arctic_blue_bridge.png ..\sbgck-dev-game\src\boards\Arctic-base.png	33_arctic_x_cut_blue_bridge.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 40_arctic_yellow_control_post.png ..\sbgck-dev-game\src\boards\Arctic-base.png	40_arctic_x_cut_yellow_control_post.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 41_arctic_yellow_living_room.png ..\sbgck-dev-game\src\boards\Arctic-base.png	41_arctic_x_cut_yellow_living_room.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 42_arctic_yellow_storage_room.png ..\sbgck-dev-game\src\boards\Arctic-base.png	42_arctic_x_cut_yellow_storage_room.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 43_arctic_yellow_bridge.png ..\sbgck-dev-game\src\boards\Arctic-base.png	43_arctic_x_cut_yellow_bridge.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 50_arctic_dice_white_empty.png ..\sbgck-dev-game\src\boards\Arctic-base.png	50_arctic_x_cut_dice_white_empty.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 51_arctic_dice_white_d2.png ..\sbgck-dev-game\src\boards\Arctic-base.png	51_arctic_x_cut_dice_white_d2.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 52_arctic_dice_white_d3_d4.png ..\sbgck-dev-game\src\boards\Arctic-base.png	52_arctic_x_cut_dice_white_d3_d4.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 53_arctic_dice_white_d1_d2_d3.png ..\sbgck-dev-game\src\boards\Arctic-base.png	53_arctic_x_cut_dice_white_d1_d2_d3.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 60_arctic_dice_black_empty.png ..\sbgck-dev-game\src\boards\Arctic-base.png	60_arctic_x_cut_dice_black_empty.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 61_arctic_dice_black_d2.png ..\sbgck-dev-game\src\boards\Arctic-base.png	61_arctic_x_cut_dice_black_d2.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 62_arctic_dice_black_d4_d1.png ..\sbgck-dev-game\src\boards\Arctic-base.png	62_arctic_x_cut_dice_black_d4_d1.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 63_arctic_dice_black_d4_d4_d4.png ..\sbgck-dev-game\src\boards\Arctic-base.png	63_arctic_x_cut_dice_black_d4_d4_d4.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 70_arctic_remote_full.png ..\sbgck-dev-game\src\boards\Arctic-base.png	70_arctic_x_cut_remote_full.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 71_arctic_remote_power.png ..\sbgck-dev-game\src\boards\Arctic-base.png	71_arctic_x_cut_remote_power.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 72_arctic_remote_repeat.png ..\sbgck-dev-game\src\boards\Arctic-base.png	72_arctic_x_cut_remote_repeat.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 73_arctic_remote_vol_up.png ..\sbgck-dev-game\src\boards\Arctic-base.png	73_arctic_x_cut_remote_vol_up.png
..\sbgck-opencv\dev\build\bin\Debug\main_detectboardonmap.exe 74_arctic_remote_vol_down.png ..\sbgck-dev-game\src\boards\Arctic-base.png	74_arctic_x_cut_remote_vol_down.png
