..\sbgck-opencv\dev\build\bin\Debug\main_diff_images.exe 10_arctic_x_cut_red_control_post.png	00_arctic_x_cut_calibration.png	10_arctic_x_masked_red_control_post.png
..\sbgck-opencv\dev\build\bin\Debug\main_diff_images.exe 11_arctic_x_cut_red_living_room.png	00_arctic_x_cut_calibration.png	11_arctic_x_masked_red_living_room.png
..\sbgck-opencv\dev\build\bin\Debug\main_diff_images.exe 12_arctic_x_cut_red_storage_room.png	00_arctic_x_cut_calibration.png	12_arctic_x_masked_red_storage_room.png
..\sbgck-opencv\dev\build\bin\Debug\main_diff_images.exe 13_arctic_x_cut_red_bridge.png	00_arctic_x_cut_calibration.png	13_arctic_x_masked_red_bridge.png
..\sbgck-opencv\dev\build\bin\Debug\main_diff_images.exe 20_arctic_x_cut_green_control_post.png	00_arctic_x_cut_calibration.png	20_arctic_x_masked_green_control_post.png
..\sbgck-opencv\dev\build\bin\Debug\main_diff_images.exe 21_arctic_x_cut_green_living_room.png	00_arctic_x_cut_calibration.png	21_arctic_x_masked_green_living_room.png
..\sbgck-opencv\dev\build\bin\Debug\main_diff_images.exe 22_arctic_x_cut_green_storage_room.png	00_arctic_x_cut_calibration.png	22_arctic_x_masked_green_storage_room.png
..\sbgck-opencv\dev\build\bin\Debug\main_diff_images.exe 23_arctic_x_cut_green_bridge.png	00_arctic_x_cut_calibration.png	23_arctic_x_masked_green_bridge.png
..\sbgck-opencv\dev\build\bin\Debug\main_diff_images.exe 30_arctic_x_cut_blue_control_post.png	00_arctic_x_cut_calibration.png	30_arctic_x_masked_blue_control_post.png
..\sbgck-opencv\dev\build\bin\Debug\main_diff_images.exe 31_arctic_x_cut_blue_living_room.png	00_arctic_x_cut_calibration.png	31_arctic_x_masked_blue_living_room.png
..\sbgck-opencv\dev\build\bin\Debug\main_diff_images.exe 32_arctic_x_cut_blur_storage_room.png	00_arctic_x_cut_calibration.png	32_arctic_x_masked_blur_storage_room.png
..\sbgck-opencv\dev\build\bin\Debug\main_diff_images.exe 33_arctic_x_cut_blue_bridge.png	00_arctic_x_cut_calibration.png	33_arctic_x_masked_blue_bridge.png
..\sbgck-opencv\dev\build\bin\Debug\main_diff_images.exe 40_arctic_x_cut_yellow_control_post.png	00_arctic_x_cut_calibration.png	40_arctic_x_masked_yellow_control_post.png
..\sbgck-opencv\dev\build\bin\Debug\main_diff_images.exe 41_arctic_x_cut_yellow_living_room.png	00_arctic_x_cut_calibration.png	41_arctic_x_masked_yellow_living_room.png
..\sbgck-opencv\dev\build\bin\Debug\main_diff_images.exe 42_arctic_x_cut_yellow_storage_room.png	00_arctic_x_cut_calibration.png	42_arctic_x_masked_yellow_storage_room.png
..\sbgck-opencv\dev\build\bin\Debug\main_diff_images.exe 43_arctic_x_cut_yellow_bridge.png	00_arctic_x_cut_calibration.png	43_arctic_x_masked_yellow_bridge.png